name: Flutter CI

on:
  push:
    branches:
      - master # ya "main" agar tumhara branch ka naam main ho
  pull_request:

jobs:
  build:
    name: Build & Test Flutter App
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.2'  # apni Flutter version yahan daalna

      - name: Install Dependencies
        run: flutter pub get

      - name: Analyze Code
        run: flutter analyze

      - name: Run Tests
        run: flutter test

      - name: Build APK (release)
        run: flutter build apk --release
